### ISSUE TITLE
User Story: Annonymous Feedback

### ISSUE THREAD

**Issue by MattMiles95** [MattMiles95/Love-Running-Project#1]
## User Story

In order to provide annonymous feedback as a user, I can choose to hide my identity in the poll response.

## Acceptance Criteria

1. The option should be provided as a checkbox.
2. The checkbox should be "cheked" by default.
3. The option should appear next to the submit button.
4. After submitting, the default submission confirmation should be adjusted to include the User's name.

## Tasks

- [x] Update the view: the poll design (HTML and CSS) to include the checkbox and display the name of the User
- [ ] Create a new field in the model to track the username
- [ ] Update the controller function
- [ ] Update unit test scripts
- [ ] Test the functionality
